<h1 id="objectives">Objectives</h1>
<p>The learning objectives for this practical are:</p>
<ul>
<li>Use a text editor to write your Unix scripts.</li>
<li>Chain Unix commands using pipes.</li>
<li>Extract rows and columns.</li>
<li>Sorting lines.</li>
<li>Counting occurrences.</li>
<li>Pasting columns.</li>
</ul>
<h1 id="setup-and-background">Setup and background</h1>
<p>We will download again some COVID19 data. Please follow the next two steps:</p>
<ol type="1">
<li>Go to the Catalan Health Departament COVID data portal at <a href="https://dadescovid.cat">https://dadescovid.cat</a> and switch the language to “ENGLISH” using the pull-down menu on the top-right corner of the page.</li>
<li>Follow the downloads link and on the next page click and download the two files corresponding to the “7 DAY AGGREGATION” for “CATALUNYA” and “COUNTIES” (“COMARQUES” in Catalan) for the “RESIDENCE/GENERAL” population. It is important that you download both files in the same day to make them comparable, because all data is updated daily. Make sure you know exactly where in your filesystem these two files have been downloaded. <strong>Tip:</strong> some browsers automatically download files into a folder called “Downloads” or under a name corresponding to the translation of “Downloads” to the default language of your operating system.</li>
<li>Make a directory in your filesystem, for instance at your <em>home</em> directory, called <code>practical2</code> and copy in it the CSV files contained in the previous two ZIP files that you have downloaded, as you analogously did in practical 1.</li>
</ol>
<h1 id="use-a-text-editor-to-write-your-unix-scripts.">Use a text editor to write your Unix scripts.</h1>
<p>If you have not done so yet, please download an install a text editor application in your computer, following the <a href="/setup/">setup</a> instructions. Once the text editor application is installed, run it as follows:</p>
<ul>
<li><p>If you have installed a <em>classical</em> text editor, open the editor in a new terminal window. Classical editors are tipically called from the Unix shell and it’s handy to given them the name of the file you want to edit right way as you called them as a first argument. If you do that, give them the filename <code>practical2.sh</code>.</p></li>
<li><p>If you have installed a <em>modern</em> text editor, open it by starting the application from the graphical user interface of your computer.</p></li>
</ul>
<p>Once the text editor application is running, write the following two lines on a new fresh empty text file:</p>
<pre><code>## Script for practical 2
</code></pre>
<p>Save these contents into a file called <code>practical2.sh</code> located at the directory <code>practical2</code> that you created before. During the rest of this practical, write all the Unix commands that you type in the terminal also in the text file. Please don’t type them twice, first type them in the terminal window and once they work, then select the command-line using the mouse and finally copy and paste it into the text editor. Each time you copy a new line, save the file again. To keep a better record of what you are doing, add above each shell line a shell comment line, which always starts with one or more hash characters (<code>#</code>), for <strong>example</strong>:</p>
<pre><code>## list the files
ls</code></pre>
<p>Once you have some Unix commands in your script file, and you have save it to disk, you may execute that script from the Unix shell as follows (assuming you saved the script as <code>practical2.sh</code>):</p>
<pre><code>$ sh practical2.sh</code></pre>
<p><strong>Tip:</strong> when writing shell scripts you will likely introduce syntax errors, which sometimes may be difficult to identify. To help you in identifying those errors you may use the website <a href="https://www.shellcheck.net">https://www.shellcheck.net</a>. To use it you should paste into the main text box the following line, known as <a href="https://en.wikipedia.org/wiki/Shebang_%28Unix%29">shebang</a>:</p>
<pre><code>#!/bin/sh</code></pre>
<p>and afterwords paste the line, or lines, for which you want to check the syntax of your shell script. The website will parse your script and tell you that either issues were not detected or what syntax errors have been encountered.</p>
<h1 id="chain-unix-commands-using-pipes">Chain Unix commands using pipes</h1>
<p>In the previous practical we have seen how to redirect the terminal output to a file. In this section we are going to see a similar concept, where instead of redirecting the terminal output created by a Unix command to a file, we will redirect that terminal output as input into <strong>another Unix command</strong> by using what is known as a <a href="https://en.wikipedia.org/wiki/Pipeline_%28Unix%29">Unix pipeline</a>, or Unix pipe for short. The concept of Unix pipes was created by <a href="https://en.wikipedia.org/wiki/Douglas_McIlroy">Douglas McIlroy</a>, which is based on his widely adopted view of the <a href="https://en.wikipedia.org/wiki/Unix_philosophy">Unix philosophy</a>:</p>
<blockquote>
<p>Write programs that do one thing and do it well. Write programs to work together. Write programs to handle text streams, because that is a universal interface.</p>
</blockquote>
<p>To use the Unix pipe we should place the vertical bar (<code>|</code>), available in Spanish keyboards by pressing <code>AltGr+1</code>, between two Unix commands. Try the following:</p>
<pre><code>$ cat catalunya_setmanal.csv | head</code></pre>
<p>Notice that while the <code>cat</code> command should have sent the output of the <strong>whole</strong> text file to the terminal window, we only see the first few lines of that output. This has occurred because the pipe has sent that whole output from the <code>cat</code> command to the input of the <code>head</code> command, which only shows the first few lines of that input. This can be graphically represented as follows:</p>
<p><img src="singlepipe.png" style="display: block; margin-left: auto; margin-right: auto; width: 50%; height: auto;"></p>
<h1 id="extract-rows-and-columns">Extract rows and columns</h1>
<p>Text files such as CSV files have a matrix layout with rows corresponding to lines and columns to values separated by some delimiter character, which is a semicolon (<code>;</code>) in the case of the previous file <code>catalunya_setmanal.csv</code>. Because of its matrix layout, a CSV file can be always opened by any spreadsheet software, such as Microsoft Excel; see image below.</p>
<p><img src="ExcelCSV.png" style="display: block; margin-left: auto; margin-right: auto; width: 80%; height: auto;"></p>
<p>However, there are at least two circumstances in which working with CSV files from the Unix command-line is preferable to do it from a spreadsheet software such as Microsoft Excel:</p>
<ol type="1">
<li>Spreadsheet software will always attempt to load the whole data into main memory. This may become prohibitive when having tens of thousands of rows, which is common for data with molecular-level measurements from high-thoughput instruments.</li>
<li>Every spreadsheet software uses its own format to store the data, which makes it prone to <a href="https://en.wikipedia.org/wiki/Digital_obsolescence">digital obsolescence</a>, the fact that old software required to open a file is no longer available. CSV files, and text files in general, can never become obsolete because their format does not depend on any specific software to be read or written.</li>
</ol>
<p>Additionally, the misuse of Microsoft Excel has caused multiple problems with important consequences in loss of monetary and human-time resources, such as the <a href="https://www.theguardian.com/politics/2020/oct/05/how-excel-may-have-caused-loss-of-16000-covid-tests-in-england">loss in 2020 of COVID19-test results in England</a>.</p>
<p>Here we will learn to do two common operations on data organized in a matrix layout: extract rows (lines) and extract columns (delimiter-separated values). To extract rows from a text file in Unix we will use the command <code>grep</code>, which requires two pieces of information:</p>
<pre><code>$ grep pattern filename</code></pre>
<p>where <code>pattern</code> is the text that we expect to match to the lines we want to extract, while <code>filename</code> is the name of the file from which we want to extract the lines matching the pattern. Note that <code>pattern</code> can be something sophisticated such as a <a href="https://en.wikipedia.org/wiki/Regular_expression">regular expression</a> (not covered in this practical) and <code>filename</code> can be ommitted when we want <code>grep</code> to read input from a pipe.</p>
<p>For instance, the column <code>RESIDENCIA</code> in the COVID19 data indicates whether the row contains data derived from geriatric-care residences (value <code>Si</code>) or not (value <code>No</code>). You can check the <a href="https://dadescovid.cat/documentacio?lang=eng">documentation</a> at the Catalan COVID19 data portal to understand why the data is provided separately for these two types of population.</p>
<p>Let’s say we want to extract the rows for the COVID19 data derived from the population in Catalunya that does not live in geriatric-care residences into a separate file called <code>catalunya_setmanal_general.csv</code>.</p>
<pre><code>$ grep No catalunya_setmanal.csv &gt; catalunya_setmanal_general.csv</code></pre>
<p>Now, repeat the command but this time extracting the rows corresponding to the population that <strong>does live</strong> in geriatric-care residences into a separate file called <code>catalunya_setmanal_geriatric.csv</code>.</p>
<p><strong>Tip</strong>: note that <code>grep</code> has worked well for this particular task because no other column in the data has used the terms <code>Si</code> and <code>No</code> for any other purpose. The <code>grep</code> command doesn’t know about columns, it only finds matches of a pattern in lines, reporting the lines that match the pattern. You can also ask <code>grep</code> to report the lines that <strong>do not</strong> match the pattern by using the option <code>-v</code>.</p>
<p><strong>Warning</strong>: when using the terminal output redirection mechanism (<code>&gt;</code>) you should <strong>never</strong> use as output filename the filename that is being used as input in the same command line, because that would lead to overwriting the input file and ending with a corrupted output or without output at all.</p>
<p>Extracting columns can be done using the Unix command <code>cut</code>, which in the case of CSV files also requires specifying the options <code>-d</code> and <code>-f</code>:</p>
<pre><code>$ cut -d &#39;delimiter&#39; -f field filename</code></pre>
<p>The option <code>-d</code> allows us to specify a <a href="https://en.wikipedia.org/wiki/Delimiter">delimiter character</a>, which by default is the <a href="https://en.wikipedia.org/wiki/Tab_key">TAB character</a> and should be always specified between single quotes (e.g., <code>','</code>). The option <code>-f</code> allows us to specify the columns, also known as <a href="https://en.wikipedia.org/wiki/Data_field">fields</a> in this context. For instance, let’s say we want to extract the last column of the CSV file <code>catalunya_setmanal.csv</code>, corresponding to the number of exitus at each 7-day agggregation period. Taking into account that this file uses the semicolon (<code>;</code>) as field separator, we should write:</p>
<pre><code>$ cut -d &#39;;&#39; -f 17 catalunya_setmanal.csv | head</code></pre>
<p>Now let’s say we want to extract this column from the geriatric subset of the data. We could either run the previous command on the file we created before:</p>
<pre><code>$ cut -d &#39;;&#39; -f 17 catalunya_setmanal_geriatric.csv | head</code></pre>
<p>or had we not generated that file, we could have done it from the original data file using two pipes, as follows:</p>
<pre><code>$ grep Si catalunya_setmanal.csv | cut -d &#39;;&#39; -f 17 | head</code></pre>
<p>Note that in both cases the output is identical.</p>
<h1 id="sort-rows">Sort rows</h1>
<p>Unix provides a command called <code>sort</code> to order rows of a file in a number of ways. By default, it sorts rows in increasing alphabetical order. Note for instance that in the <code>catalunya_setmanal.csv</code> file, the column <code>DATA_INI</code> and <code>DATA_FI</code> contain the initial and end date of the recorded data for each row, that first lines correspond to more recent data and that date is written in a format that the alphabetic order matches the time order. Type the following four commands:</p>
<pre><code>$ cut -d &#39;;&#39; -f 3,17 catalunya_setmanal.csv | head
$ cut -d &#39;;&#39; -f 3,17 catalunya_setmanal.csv | tail
$ cut -d &#39;;&#39; -f 3,17 catalunya_setmanal.csv | sort | head
$ cut -d &#39;;&#39; -f 3,17 catalunya_setmanal.csv | sort | tail</code></pre>
<p>Looking at the output of each them, can you explain their differences?</p>
<h2 id="influence-of-the-locale-regional-configuration-of-your-system">Influence of the locale (regional) configuration of your system</h2>
<p>When you use the <code>sort</code> command to order numbers, you should use the option <code>-n</code>. This option is valid for both, integer and real numbers (i.e., with decimal digits). However, in this latter case, there is a complication derived from the different existing conventions to separate the integer from the decimal part of such a number, e.g., 1.5 vs 1,5.</p>
<p>Every computer and operating system works with a so-called <a href="https://en.wikipedia.org/wiki/Locale_%28computer_software%29">locale configuration</a> that defines the language used on the computer as well as every other regional aspect influencing how the user reads and writes information on the computer. One of those aspects is the decimal number separator, which in English-speaking countries is the dot (<code>.</code>) and, for instance, in Spain is the comma (<code>,</code>).</p>
<p>The <code>sort</code> command looks up what is the current <em>locale configuration</em>, and particularly, what is the decimal number separator, to decide how to sort numbers when we specify the <code>-n</code> option. If our configuration is set up to use comma (<code>,</code>) as decimal separator but the data we want to sort uses the dot <code>.</code>, then we need to either replace those dots by commas or change our <em>locale configuration</em> to an English-speaking one.</p>
<p>To figure out our current <em>locale configuration</em> type the <code>locale</code> command on the Unix shell (the output shown below is one possible example of output, not necessarily the one you obtain in your computer):</p>
<pre><code>$ locale
LANG=&quot;&quot;
LC_COLLATE=&quot;ca_ES&quot;
LC_CTYPE=&quot;ca_ES&quot;
LC_MESSAGES=&quot;ca_ES&quot;
LC_MONETARY=&quot;ca_ES&quot;
LC_NUMERIC=&quot;ca_ES&quot;
LC_TIME=&quot;ca_ES&quot;
LC_ALL=&quot;ca_ES&quot;</code></pre>
<p>You can also verify how the <code>sort</code> command is picking up that locale configuration on the decimal number separator by using the options <code>-n --debug</code> as follows:</p>
<pre><code>$ sort -n --debug
Using collate rules of ca_ES locale
Decimal Point: &lt;,&gt;
Positive sign: &lt;+&gt;
Negative sign: &lt;-&gt;</code></pre>
<p>If you typed the previous instruction, you need to press <code>Ctrl+d</code> to exit the <code>sort</code> command since we are not giving any file to sort in the previous call. If <strong>you need</strong> to change the <em>locale</em> into an English-speaking configuration in an Unix system such as Ubuntu you should type the following:</p>
<pre><code>$ LC_ALL=en_US</code></pre>
<p>You can verify that the <em>locale configuration</em> has changed.</p>
<pre><code>$ locale
LANG=&quot;&quot;
LC_COLLATE=&quot;en_US&quot;
LC_CTYPE=&quot;en_US&quot;
LC_MESSAGES=&quot;en_US&quot;
LC_MONETARY=&quot;en_US&quot;
LC_NUMERIC=&quot;en_US&quot;
LC_TIME=&quot;en_US&quot;
LC_ALL=&quot;en_US&quot;
$ sort -n --debug
Using collate rules of en_US locale
Decimal Point: &lt;.&gt;
Thousands separator: &lt;,&gt;
Positive sign: &lt;+&gt;
Negative sign: &lt;-&gt;</code></pre>
<p>If you are on Windows using the <em>Git Bash</em> Unix shell emulator or on macOS using the Terminal application, then please check the corresponding instructions on the <a href="/setup/">setup</a> page, in the section about how to install a Unix shell.</p>
<p>Once you have configured your system with an English-speaking <em>locale configuration</em>, then you can safely sort decimal numbers on files with the dot (<code>.</code>) as decimal number separator. You can check whether it works by trying to reverse order the real numbers 0.11, 2.22 and 5.0, as follows:</p>
<pre><code>$ echo -e &#39;0.11\n2.22\n5.0&#39; | sort -nr --debug
Using collate rules of en_US.UTF-8 locale
Decimal Point: &lt;.&gt;
Positive sign: &lt;+&gt;
Negative sign: &lt;-&gt;
5.0
2.22
0.11</code></pre>
<h1 id="remove-consecutive-duplicated-lines">Remove consecutive duplicated lines</h1>
<p>The Unix command <code>uniq</code> removes consecutive duplicated lines. Look for instance at the beginning and the end of the file <code>comarques_setmanal.csv</code>:</p>
<pre><code>$ head comarques_setmanal.csv
NOM;CODI;DATA_INI;DATA_FI;RESIDENCIA;IEPG_CONFIRMAT;R0_CONFIRMAT_M;IA14;TAXA_CASOS_CONFIRMAT;CASOS_CONFIRMAT;TAXA_PCRTAR;PCR;TAR;PERC_PCRTAR_POSITIVES;INGRESSOS_TOTAL;INGRESSOS_CRITIC;EXITUS;CASOS_PCR;CASOS_TAR;POSITIVITAT_PCR_NUM;POSITIVITAT_TAR_NUM;POSITIVITAT_PCR_DEN;POSITIVITAT_TAR_DEN;VACUNATS_DOSI_1;VACUNATS_DOSI_2
ALT CAMP;01;2021-09-19;2021-09-25;No;36.2005;1.14456;31.6191;9.0340;4;1300.9011;292;284;0.7707;0;0;0;2;2;2;2;252;267;175;183
ALT CAMP;01;2021-09-19;2021-09-25;Si;;;0.0000;0.0000;0;1740.8123;8;1;0.0000;0;0;0;0;0;0;0;3;0;3;2
ALT CAMP;01;2021-09-18;2021-09-24;No;41.2068;1.21599;33.8776;13.5510;6;1307.6766;302;277;1.3487;0;0;0;2;4;3;4;260;259;172;185
ALT CAMP;01;2021-09-18;2021-09-24;Si;;;0.0000;0.0000;0;1547.3887;7;1;0.0000;0;0;0;0;0;0;0;2;0;3;2
ALT CAMP;01;2021-09-17;2021-09-23;No;44.9867;1.24456;36.1361;15.8095;7;1287.3500;302;268;1.7717;0;0;0;3;4;5;4;259;249;206;239
ALT CAMP;01;2021-09-17;2021-09-23;Si;;;0.0000;0.0000;0;1547.3887;7;1;0.0000;0;0;0;0;0;0;0;4;0;3;1
ALT CAMP;01;2021-09-16;2021-09-22;No;51.5783;1.26837;40.6531;15.8095;7;1271.5405;312;251;1.8293;0;0;0;3;4;5;4;263;229;171;237
ALT CAMP;01;2021-09-16;2021-09-22;Si;;;0.0000;0.0000;0;1547.3887;7;1;0.0000;0;0;0;0;0;0;0;4;0;2;1
ALT CAMP;01;2021-09-15;2021-09-21;No;36.0476;0.839796;42.9116;15.8095;7;1271.5405;332;231;1.8293;1;0;1;3;4;5;4;282;210;205;253


$ tail comarques_setmanal.csv 
VALLES ORIENTAL;41;2020-02-28;2020-03-05;No;;;0.2422;0.2422;1;2.4223;10;0;0.0000;0;0;0;1;0;0;0;10;0;0;0
VALLES ORIENTAL;41;2020-02-28;2020-03-05;Si;;;0.0000;0.0000;0;0.0000;0;0;0.0000;0;0;0;0;0;0;0;0;0;0;0
VALLES ORIENTAL;41;2020-02-27;2020-03-04;No;;;0.2422;0.2422;1;1.9379;8;0;0.0000;0;0;0;1;0;0;0;8;0;0;0
VALLES ORIENTAL;41;2020-02-27;2020-03-04;Si;;;0.0000;0.0000;0;0.0000;0;0;0.0000;0;0;0;0;0;0;0;0;0;0;0
VALLES ORIENTAL;41;2020-02-26;2020-03-03;No;;;0.2422;0.2422;1;1.6956;7;0;0.0000;0;0;0;1;0;0;0;7;0;0;0
VALLES ORIENTAL;41;2020-02-26;2020-03-03;Si;;;0.0000;0.0000;0;0.0000;0;0;0.0000;0;0;0;0;0;0;0;0;0;0;0
VALLES ORIENTAL;41;2020-02-25;2020-03-02;No;;;0.0000;0.0000;0;1.2111;5;0;0.0000;0;0;0;0;0;0;0;5;0;0;0
VALLES ORIENTAL;41;2020-02-25;2020-03-02;Si;;;0.0000;0.0000;0;0.0000;0;0;0.0000;0;0;0;0;0;0;0;0;0;0;0
VALLES ORIENTAL;41;2020-02-24;2020-03-01;No;;;0.0000;0.0000;0;0.7267;3;0;0.0000;0;0;0;0;0;0;0;3;0;0;0
VALLES ORIENTAL;41;2020-02-24;2020-03-01;Si;;;0.0000;0.0000;0;0.0000;0;0;0.0000;0;0;0;0;0;0;0;0;0;0;0</code></pre>
<p>Lines appear to be grouped by county name, which occurs in the first column. Let’s extract the first column, apply the <code>uniq</code> command on its output and count the number of resulting lines:</p>
<pre><code>$ cut -f 1 -d &#39;;&#39; comarques_setmanal.csv | uniq | wc -l
      43</code></pre>
<p>Do you know to what corresponds this number?</p>
<p>In this case, duplicated lines were occurring in consecutively one after each other. However, if this were not the case, what do you think we could do before using the <code>uniq</code> command to bring duplicated lines together?</p>
<h1 id="count-consecutive-occurrences">Count consecutive occurrences</h1>
<p>In a previous practical, we have seen the command <code>wc</code>, which can be employed to count the lines of a text file. Here we want to learn the command <code>uniq</code> with its option <code>-c</code>, which allows one to count consecutively repeated lines. This is useful to count occurrences of interest in a file. For instance, let’s say we want to count the number of different exitus occurrences in the file <code>catalunya_setmanal.csv</code>, i.e., how many lines (7-days aggregation periods) reported 0 exitus, how many reported 1, how many reported 2, etc. We need to extract the exitus column (17), sort it and apply the <code>uniq -c</code> command:</p>
<pre><code>$ cut -f 17 -d &#39;;&#39; catalunya_setmanal.csv | sort | uniq -c | head</code></pre>
<p>Let’s say we want to see the most frequent occurrences first. We would need then to sort the previous output numerically (option <code>-n</code>) and from largest to smallest (option <code>-r</code>), as follows:</p>
<pre><code>$ cut -f 17 -d &#39;;&#39; catalunya_setmanal.csv | sort | uniq -c | sort -n -r | head
    241 0
    129 1
     91 2
     68 3
     39 4
     36 5
     28 12
     23 6
     23 10
     22 9</code></pre>
<p>So the most frequent reported exitus figure was 0 in 241 7-day aggregation periods (lines in the CSV file), the second most frequent one was 1 exitus in 129 lines, and so on. We can also tell <code>sort</code> to order that output by the second column using the option <code>-k</code>, which would give us the whole ordered frequency distribution of exitus:</p>
<pre><code>$ cut -f 17 -d &#39;;&#39; catalunya_setmanal.csv | sort | uniq -c | sort -n -k 2 | head -20
      1 EXITUS
    241 0
    129 1
     91 2
     68 3
     39 4
     36 5
     23 6
     21 7
     13 8
     22 9
     23 10
     18 11
     28 12
     15 13
     17 14
     17 15
     13 16
     17 17
     16 18</code></pre>
<h1 id="paste-columns">Paste columns</h1>
<p>The Unix command <code>paste</code> allows us to paste in parallel lines of given files using a <code>TAB</code> as delimiter character by default, which can be changed with the option <code>-d</code>. For instance, see what happens when extract two columns from the CSV file and paste them again:</p>
<pre><code>$ cut -d &#39;;&#39; -f 3 catalunya_setmanal.csv &gt; catalunya_setmanal_dataini.csv
$ cut -d &#39;;&#39; -f 17 catalunya_setmanal.csv &gt; catalunya_setmanal_exitus.csv
$ paste catalunya_setmanal_dataini.csv catalunya_setmanal_exitus.csv | head
DATA_INI      EXITUS
2021-09-19    30
2021-09-19    0
2021-09-19    5
2021-09-18    33
2021-09-18    0
2021-09-18    4
2021-09-17    0
2021-09-17    7
2021-09-17    29</code></pre>
<h1 id="exercises">Exercises</h1>
<p>Using the Unix commands we have learned in this practical, try to answer the questions below about the downloaded COVID19 data. Try to edit a shell script for each question under the filename, for instance, <code>question1.sh</code>, <code>question2.sh</code>, etc., and execute it from the shell as, for instance:</p>
<pre><code>$ sh question1.sh</code></pre>
<h3 id="question-1">Question 1</h3>
<p>For how many 7-day aggregation periods do we have COVID19 data for the general population (i.e., excluding those living in geriatric residences) in Catalunya? (answer: 574 on September 29th, 2021)</p>
<h3 id="question-2">Question 2</h3>
<p>Which is the highest <a href="https://en.wikipedia.org/wiki/Basic_reproduction_number">basic reproduction number</a> (R0, column <code>R0_CONFIRMAT</code>) observed for the general population (i.e., excluding those living in geriatric residences) in Catalunya throughout the whole 7-day aggregation periods? (answer 4.99) and for the months of June 2020 and June 2021? (answer 1.69 and 3.47)</p>
<h3 id="question-3">Question 3</h3>
<p>In which 7-day aggregation period was the R0 highest for the general population? (<strong>Hint:</strong> you can use the <code>sort</code> command with the options <code>-k</code> to use a particular column for sorting and <code>-t</code> to indicate the column delimiter character different form the default, which is the blank character <code>' '</code>. Answer: 2020-03-09)</p>
<h3 id="question-4">Question 4</h3>
<p>Which county had the highest number of exitus in geriatric residences? In which 7-day aggregation period did that happen? (answer: BARCELONES, 573 exitus between 2020-04-06 and 2020-04-12)</p>
<h3 id="question-5">Question 5</h3>
<p>Compare the number of exitus among the general population (i.e., excluding geriatric residences) in the month of March 2020 between two of your favorite Catalan counties. For instance, this would be the output for <code>SEGRIA</code> (left) and <code>OSONA</code> (right):</p>
<pre><code>11      52
10      53
11      56
13      52
14      52
14      49
12      50
13      40
13      38
12      34
10      36
9       30
6       23
7       16
4       17
2       14
2       12
2       8
2       6
1       6
0       4
0       1
0       1
0       1
0       1
0       0
0       0
0       0
0       0
0       0
0       0</code></pre>
